version: '3.8'
services:
  backend:
    build: ./demo-1
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    depends_on:
      - frontend

  frontend:
    build: ./angular_frontend
    container_name: angular-app
    ports:
      - "4200:80"
