name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Run the pipeline when pushing to 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Java and Maven for Spring Boot
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Set up Node.js for Angular
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      # Build Angular App
      - name: Install Dependencies & Build Angular
        run: |
          cd angular-frontend
          npm install
          npm run build --configuration=production

      # Build Spring Boot App
      - name: Build Spring Boot with Maven
        run: |
          cd demo-1
          mvn clean package -DskipTests

      - name: Install SSH Key
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i private_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_IP }} << 'EOF'
          set -e

          sudo apt update
          sudo apt install -y docker.io docker-compose
          sudo systemctl start docker
          sudo systemctl enable docker
          sudo usermod -aG docker ubuntu


          cd CICD-demo  
          git reset --hard origin/master
          git pull origin master  
          sudo docker-compose down 
          sudo docker-compose up -d --build 
          EOF
